{
 "title": "Przykładowy dashboard",
 "description": "I love sekurak!",
 "tags": [
  "test",
  "sekurak",
  "Zabbix"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Grafana - parametr w_await",
   "type": "histogram",
   "description": "Rozkład średnich czasów (w milisekundach) obsługi żądań zapisu wysłanych do dysku “sda” z serwera Grafany (lub inaczej - parametr “w_await” z polecenia iostat)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "grafana-12-1" },
     "item": {
      "filter": "sda: Disk write request avg waiting time (w_await)"
     },
     "itemTag": { "filter": "component: storage" },
     "itemids": "50058",
     "macro": { "filter": "/.*/" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Zabbix server - CPU vs RAM",
   "type": "xychart",
   "description": "Wykres zależności obciążenia CPU w porównaniu do pamięci (w %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Zabbix servers" },
     "host": { "filter": "zabbix-7-0" },
     "item": {
      "filter": "/CPU utilization|Memory utilization/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "false",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "state-timeline",
   "description": "Status wartości LOAD w zależności od ilości jednostek CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "grafana-12-1" },
     "item": { "filter": "/Load average .*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median",
           "first",
           "last"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "$__range",
        "last"
       ],
       "text": "groupBy(1m, avg)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "grafana-12-1" },
     "item": { "filter": "Number of CPUs" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Ruch sieciowy",
   "type": "netsage-sankey-panel",
   "description": "Wykres przedstawiający ruch sieciowy na serwerach zabbix-7-0 oraz grafana-12-1",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/Interface .*: Bits (sent|received)/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}